### ISSUE TITLE
hex2rgba Error after installation

### ISSUE THREAD

**Issue by rijdz** [MunifTanjim/gatsby-theme-dox#2]
how properly install your theme ?
I only could make it work by cloned your repo and used yarn add gatsby-theme-dox  to install everything.

Whenever I install another package from npm it always said 
"hex2rgba: first argument has invalid hexadecimal characters"

Then the theme cannot be used anymore

**Comment by MunifTanjim** [comment]
@rijdz the latest version ([`v0.3.0`](https://www.npmjs.com/package/gatsby-theme-dox/v/0.3.0)) dropped dependency on `hex2rgba` package. It should be fixed now.
